### ISSUE TITLE
GetPageLinks fail: duplicate keys for query String (limit...) and throwns exception

### ISSUE THREAD

**Issue by aseguragonzalez** [TryCatch-SoftwareFactory/TryCatch.Hateoas#11]
**Exception details**
System.ArgumentException: An item with the same key has already been added. Key: limit
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.IDictionaryExtensions.NormalizedKeys(IDictionary`2 keys, IDictionary`2 normalizedKeys)
   at System.Collections.Generic.IDictionaryExtensions.MergeWith(IDictionary`2 current, IDictionary`2 keysToMerge)
   at TryCatch.Hateoas.Models.Link.AddOrUpdateQueryParam(IDictionary`2 queryParams)
   at TryCatch.Hateoas.Services.LinksService.<>c__DisplayClass8_0.<GetPageLinks>b__1(LinkInfo x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at TryCatch.Hateoas.Services.LinksService.GetPageLinks(Int64 offset, Int64 limit, Int64 total, IDictionary`2 defaultQueryParams, IEnumerable`1 templates, Int32 maxNumberOfPages, String pageRel, String pageAction)

**Settings**
```csharp
/// <summary>
/// Gets the link collection template for a device.
/// </summary>
public static IEnumerable<LinkInfo> GetLinkTemplate =>
    new HashSet<LinkInfo>()
    {
       new LinkInfo("edit", "UPDATE"),
       new LinkInfo("remove", "DELETE"),
       new LinkInfo("self", "GET"),
    };

/// <summary>
/// Gets the template for the page link collection.
/// </summary>
public static IEnumerable<LinkInfo> GetPageLinkTemplate => new HashSet<LinkInfo>()
    {
       new LinkInfo("search", "GET", new Dictionary<string, string>() { { "search", string.Empty } }),
       new LinkInfo("orderBy", "GET", new Dictionary<string, string>() { { "orderBy", string.Empty } }),
       new LinkInfo("sortAs", "GET", new Dictionary<string, string>() { { "sortAs", string.Empty } }),
       new LinkInfo("limit", "GET", new Dictionary<string, string>() { { "limit", string.Empty } }),
    };

/// <summary>
/// Gets the default key-value parameters for query string.
/// </summary>
public static IDictionary<string, string> GetDefaultParams => new Dictionary<string, string>()
    {
        { "offset", "1" },
        { "limit", "40" },
        { "orderBy", "DeviceId" },
        { "sortAs", "ASC" },
    };
```

**Comment by aseguragonzalez** [comment]
Duplication occurs when queryString parameters and defaults are not camelcase normalized
